author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /babb-test2
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://images.readux.ecds.emory.edu:8443/cantaloupe/iiif/2/9925a938-00ad-41c4-9281-534aceb1dfc1_MSS0796-B001-F001-I001-P000-PROD.jpg/full/full/0/default.jpg
image_size:
  page:
    height: 2535
    width: 3879
permalink: pretty
publication_info:
  date: '2021'
  editors: []
  title: "Phillis Wheatley \u201CJoining Copies\u201D small copybook"
show_annotation_author: true
source_info:
  title: "Phillis Wheatley \u201CJoining Copies\u201D small copybook"
  via_readux: true
tagline: an annotated digital edition
title: "Phillis Wheatley \u201CJoining Copies\u201D small copybook"
url: https://jpkarlsberg.github.io
version: 0.7
